### ISSUE TITLE
Undo/Redo error: addUndoPosition called while storedDescription=Modify Shock cord description=Modify Body tube

### ISSUE THREAD

**Issue by kruland2607** [openrocket/openrocket#113]
Reported automatically:

net.sf.openrocket.gui.main.SwingExceptionHandler$InternalException: Undo/Redo error: addUndoPosition called while storedDescription=Modify Shock cord description=Modify Body tube
    at net.sf.openrocket.gui.main.SwingExceptionHandler.handleErrorCondition(SwingExceptionHandler.java:101)
    at net.sf.openrocket.document.OpenRocketDocument.logUndoError(OpenRocketDocument.java:561)
    at net.sf.openrocket.document.OpenRocketDocument.addUndoPosition(OpenRocketDocument.java:321)
    at net.sf.openrocket.gui.configdialog.ComponentConfigDialog.showDialog(ComponentConfigDialog.java:193)
    at net.sf.openrocket.gui.scalefigure.RocketPanel.handleComponentClick(RocketPanel.java:577)
    at net.sf.openrocket.gui.scalefigure.RocketPanel.handleMouseClick(RocketPanel.java:535)
    at net.sf.openrocket.gui.scalefigure.RocketPanel.access$100(RocketPanel.java:90)
    at net.sf.openrocket.gui.scalefigure.RocketPanel$2.mouseClicked(RocketPanel.java:204)
    at java.awt.Component.processMouseEvent(Unknown Source)
    at javax.swing.JComponent.processMouseEvent(Unknown Source)
    at java.awt.Component.processEvent(Unknown Source)
    at java.awt.Container.processEvent(Unknown Source)
    at java.awt.Component.dispatchEventImpl(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Window.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by dkingsley** [comment]
I can not reproduce this exception, tested undo/redo shock chords on a variety of ork and rkt files. further tested with other components with no issues. I recommend that this issue be closed.

**Comment by hcraigmiller** [comment]
I have tried every variation that I can think of to reproduce this error, and could not. If no one else can replicate the original error, perhaps we should close this, as @dkingsley recommended on 06/20/2017.
