### ISSUE TITLE
java.lang.IllegalArgumentException: This dataset already contains a series with the key Sustainer: Position parallel to wind (ft)

### ISSUE THREAD

**Issue by kruland2607** [openrocket/openrocket#114]
Reported automatically:

java.lang.IllegalArgumentException: This dataset already contains a series with the key Sustainer: Position parallel to wind (ft)
    at org.jfree.data.xy.XYSeriesCollection.addSeries(XYSeriesCollection.java:153)
    at net.sf.openrocket.gui.plot.SimulationPlot.<init>(SimulationPlot.java:174)
    at net.sf.openrocket.gui.plot.SimulationPlotDialog.<init>(SimulationPlotDialog.java:47)
    at net.sf.openrocket.gui.plot.SimulationPlotDialog.showPlot(SimulationPlotDialog.java:163)
    at net.sf.openrocket.gui.plot.SimulationPlotPanel$7.actionPerformed(SimulationPlotPanel.java:310)
    at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)

This problem is because the version of JFreeChart we use requires each series name to be unique.

**Comment by dkingsley** [comment]
Looks like Kevin already fixed this one, Recommend it be closed.

**Comment by hcraigmiller** [comment]
As noted by @dkingsley on 06/20/2017, this issue appears to have been resolved and should be closed.

**Comment by JoePfeiffer** [comment]
It even looks like #130 fixed it.
