### ISSUE TITLE
Bugs in Optimization process

### ISSUE THREAD

**Issue by kruland2607** [openrocket/openrocket#117]
Reported Automatically:

Three sets of fins on dual stage rocket, tried to optimize position on all 3 and ntohing changed, removed
one and ran optimize. Then clicked on the bottom of the two remaining in the top left list of current parameters.
That click returned the error.

net.sf.openrocket.util.BugException: BUG: setValueAt with invalid row:  value=0.0 row=2 column=2 selectedModifiers.size=2 selectedModifiers=[GenericModifier[modifiedClass=net.sf.openrocket.rocketcomponent.FreeformFinSet, methodName=PositionValue, multiplier=1.0], GenericModifier[modifiedClass=net.sf.openrocket.rocketcomponent.FreeformFinSet, methodName=PositionValue, multiplier=1.0]] selectedModifierTable.getRowCount=2
    at net.sf.openrocket.gui.dialogs.optimization.GeneralOptimizationDialog$ParameterSelectionTableModel.setValueAt(GeneralOptimizationDialog.java:1412)
    at javax.swing.JTable.setValueAt(Unknown Source)
    at javax.swing.JTable.editingStopped(Unknown Source)
    at javax.swing.AbstractCellEditor.fireEditingStopped(Unknown Source)
    at javax.swing.AbstractCellEditor.stopCellEditing(Unknown Source)
    at net.sf.openrocket.gui.components.DoubleCellEditor.stopCellEditing(DoubleCellEditor.java:45)

**Comment by dkingsley** [comment]
I have done some simple testing and can not reproduce this error. Recommend we close it.

**Comment by itshanney** [comment]
Closing as error is not reproduced. Please reopen if encountered again.
