### ISSUE TITLE
Optimization bug

### ISSUE THREAD

**Issue by kruland2607** [openrocket/openrocket#119]
Reported automatically:

java.lang.IllegalStateException: Point[0.0, 0.005208333333333389, 0.3333333333333333] is not in function cache.  functionCache={}  futureMap={Point[0.0, 0.005208333333333389, 0.8333333333333333]=java.util.concurrent.FutureTask@dc3b9e, Point[0.0, 0.005208333333333389, 0.3333333333333333]=java.util.concurrent.FutureTask@ce33c0, Point[0.5, 0.005208333333333389, 0.3333333333333333]=java.util.concurrent.FutureTask@1a78fff, Point[0.0, 0.5052083333333334, 0.3333333333333333]=java.util.concurrent.FutureTask@1dedb4e}
    at net.sf.openrocket.optimization.general.ParallelExecutorCache.getValue(ParallelExecutorCache.java:237)
    at net.sf.openrocket.optimization.general.multidim.MultidirectionalSearchOptimizer.optimize(MultidirectionalSearchOptimizer.java:218)
    at net.sf.openrocket.gui.dialogs.optimization.OptimizationWorker.run(OptimizationWorker.java:112)

**Comment by dkingsley** [comment]
Without more information, I recommend we close this issue.

**Comment by itshanney** [comment]
Closing as issue is too old.
