### ISSUE TITLE
Optimization bug

### ISSUE THREAD

**Issue by kruland2607** [openrocket/openrocket#120]
net.sf.openrocket.util.BugException: BUG: Selected simulation is null: item count=0
    at net.sf.openrocket.gui.dialogs.optimization.GeneralOptimizationDialog.getSelectedSimulation(GeneralOptimizationDialog.java:1282)
    at net.sf.openrocket.gui.dialogs.optimization.GeneralOptimizationDialog.access$1900(GeneralOptimizationDialog.java:105)
    at net.sf.openrocket.gui.dialogs.optimization.GeneralOptimizationDialog$18.optimizationStepTaken(GeneralOptimizationDialog.java:813)
    at net.sf.openrocket.gui.dialogs.optimization.OptimizationWorker.processQueue(OptimizationWorker.java:205)
    at net.sf.openrocket.gui.dialogs.optimization.OptimizationWorker.access$100(OptimizationWorker.java:35)
    at net.sf.openrocket.gui.dialogs.optimization.OptimizationWorker$2.run(OptimizationWorker.java:177)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$200(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by dkingsley** [comment]
Not sure how to test this, I ran several optimizations and every thing seemed to behave with respect to selecting options and running.

**Comment by itshanney** [comment]
Closing as issue is no longer reproducing. Please reopen if found again.
