### ISSUE TITLE
Illegal multiplier value, mul=1001.33

### ISSUE THREAD

**Issue by kruland2607** [openrocket/openrocket#121]
Reported automatically:

net.sf.openrocket.gui.main.SwingExceptionHandler$InternalException: Illegal multiplier value, mul=1001.33
    at net.sf.openrocket.gui.main.SwingExceptionHandler.handleErrorCondition(SwingExceptionHandler.java:101)
    at net.sf.openrocket.gui.dialogs.ScaleDialog.doScale(ScaleDialog.java:431)
    at net.sf.openrocket.gui.dialogs.ScaleDialog.access$600(ScaleDialog.java:65)
    at net.sf.openrocket.gui.dialogs.ScaleDialog$4.actionPerformed(ScaleDialog.java:406)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2028)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2351)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:387)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:242)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:236)
    at java.awt.Component.processMouseEvent(Component.java:6414)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3275)
    at java.awt.Component.processEvent(Component.java:6179)
    at java.awt.Container.processEvent(Container.java:2083)
    at java.awt.Component.dispatchEventImpl(Component.java:4776)

**Comment by dkingsley** [comment]
If you scale a rocket by a large value like 1000.33 you can get the same exception to happen and the exception is not handled so OR crashes.

**Comment by SpamWall** [comment]
Is this from choosing "Scale" from the "Tools" menu?

**Comment by dkingsley** [comment]
Yes, then type a large scale factor into the textbox for the scale.

**Comment by hcraigmiller** [comment]
This issue can no longer be reproduced in the current unstable.

[Windows 11 Pro; Version 21H2; OS Build 22000.739; Windows Feature Experience Pack 1000.22000.739.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Comment by SiboVG** [comment]
> This issue can no longer be reproduced in the current unstable.

Confirmed.
