### ISSUE TITLE
NPE at javax.swing.plaf.basic.BasicComboBoxUI$Handler.contentsChanged(Unknown Source)

### ISSUE THREAD

**Issue by kruland2607** [openrocket/openrocket#123]
reported automatically:

java.lang.NullPointerException
    at javax.swing.plaf.basic.BasicComboBoxUI$Handler.contentsChanged(Unknown Source)
    at net.sf.openrocket.gui.adaptors.FlightConfigurationModel.fireListDataEvent(FlightConfigurationModel.java:138)
    at net.sf.openrocket.gui.adaptors.FlightConfigurationModel.stateChanged(FlightConfigurationModel.java:151)
    at net.sf.openrocket.rocketcomponent.Configuration.fireChangeEvent(Configuration.java:220)
    at net.sf.openrocket.rocketcomponent.Configuration.componentChanged(Configuration.java:228)
    at net.sf.openrocket.rocketcomponent.Rocket.fireComponentChangeEvent(Rocket.java:407)
    at net.sf.openrocket.rocketcomponent.RocketComponent.fireComponentChangeEvent(RocketComponent.java:1569)
    at net.sf.openrocket.rocketcomponent.RocketComponent.fireComponentChangeEvent(RocketComponent.java:1581)
    at net.sf.openrocket.rocketcomponent.RocketComponent.setAppearance(RocketComponent.java:443)
    at net.sf.openrocket.gui.configdialog.AppearancePanel$2.stateChanged(AppearancePanel.java:152)
    at net.sf.openrocket.util.AbstractChangeSource.fireChangeEvent(AbstractChangeSource.java:41)
    at net.sf.openrocket.util.AbstractChangeSource.fireChangeEvent(AbstractChangeSource.java:52)
    at net.sf.openrocket.appearance.AppearanceBuilder.fireChangeEvent(AppearanceBuilder.java:225)
    at net.sf.openrocket.appearance.AppearanceBuilder.setShine(AppearanceBuilder.java:107)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.sf.openrocket.gui.adaptors.DoubleModel.setValue(DoubleModel.java:764)
    at net.sf.openrocket.gui.adaptors.DoubleModel$ValueSpinnerModel.setValue(DoubleModel.java:109)
    at javax.swing.JSpinner.setValue(Unknown Source)
    at javax.swing.plaf.basic.BasicSpinnerUI$ArrowButtonHandler.actionPerformed(Unknown Source)
    at javax.swing.Timer.fireActionPerformed(Unknown Source)
    at javax.swing.Timer$DoPostEvent.run(Unknown Source)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$200(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by dkingsley** [comment]
Without more information I recommend we close this issue. I have not seen any indication of this particular error in the last 3-4 months running the unstable branch.

**Comment by itshanney** [comment]
Closing as issue has not been reproduced in latest unstable branch.
