### ISSUE TITLE
[Bug] OR 22.02.beta.05 freezes on malformed thrust curve import, throws exception in 15.03

### ISSUE THREAD

**Issue by SiboVG** [openrocket/openrocket#1919]
From [this thread on TRF](https://www.rocketryforum.com/threads/openrocket-wont-load.176381/):

A user was reporting he could no longer open OpenRocket. After further investigation, OpenRocket 15.03 threw a `java.lang.IllegalArgumentException: MALFORMED` exception:

> java.lang.IllegalArgumentException: MALFORMED
	at java.util.zip.ZipCoder.toString(ZipCoder.java:58)
	at java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:300)
	at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:122)
	at net.sf.openrocket.file.motor.ZipFileMotorLoader.load(ZipFileMotorLoader.java:56)
	at net.sf.openrocket.file.motor.GeneralMotorLoader.load(GeneralMotorLoader.java:36)
	at net.sf.openrocket.database.MotorDatabaseLoader.loadDirectory(MotorDatabaseLoader.java:124)
	at net.sf.openrocket.database.MotorDatabaseLoader.loadDatabase(MotorDatabaseLoader.java:69)
	at net.sf.openrocket.database.AsynchronousDatabaseLoader.doLoad(AsynchronousDatabaseLoader.java:103)
	at net.sf.openrocket.database.AsynchronousDatabaseLoader.access$100(AsynchronousDatabaseLoader.java:8)
	at net.sf.openrocket.database.AsynchronousDatabaseLoader$LoadingThread.run(AsynchronousDatabaseLoader.java:126)

However, OpenRocket 22.02.beta.05 just freezes, with no exception popping up.

This issue is not about solving the MALFORMED exception, but about figuring out why the beta does not throw the exception. The user should always get feedback on why something fails, instead of the program just freezing... 

The fix for the exception itself will be dealt with on the TRF, or if necessary, a new issue will be created for it.

**Comment by SiboVG** [comment]
Update: the user reported that he re-installed the beta, and now it opens just fine... So I'm just gonna close this issue, because it seems like it'll be difficult to replicate the issue now. Also, PR #1920 should reduce the likelihood of this happening again.
