### ISSUE TITLE
[Bug] Exception when opening PhotoStudio on Windows

### ISSUE THREAD

**Issue by SiboVG** [openrocket/openrocket#2336]
### Describe the bug

Exception is thrown when opening PhotoStudio on Windows.

> ---------- Bug report ----------
> 
> Please include a description about what actions you were performing when the exception occurred:
> (You can edit text directly in this window)
> 
> 1.
> 2.
> 3.
> 
> If possible, please send us the .ork file that caused the bug.
> 
> Include your email address (optional; it helps if we can contact you in case we need additional information):
> 
> 
> 
> 
> (Do not modify anything below this line.)
> ---------- Exception stack trace ----------
> com.jogamp.opengl.GLException: Unable to determine GraphicsConfiguration: WindowsWGLGraphicsConfiguration[DefaultGraphicsScreen[WindowsGraphicsDevice[type .windows, connection decon, unitID 0, handle 0x0, owner false, NullToolkitLock[obj 0x75dec7a1]], idx 0], pfdID 4, ARB-Choosen true,
> requested GLCaps[rgba 8/8/8/1, trans-rgba 0x0/0/0/0, accum-rgba 0/0/0/0, dp/st/ms 16/0/6, sample-ext default, dbl, mono , hw, GLProfile[GL2/GL4bc.hw], on-scr[.]],
> chosen GLCaps[wgl vid 4 arb: rgba 8/8/8/8, trans-rgba 0x0/0/0/0, accum-rgba 16/16/16/16, dp/st/ms 24/8/0, dbl, mono , hw, GLProfile[GL2/GL4bc.hw], on-scr[.]]] at jogamp.opengl.windows.wgl.awt.WindowsAWTWGLGraphicsConfigurationFactory.chooseGraphicsConfigurationImpl(WindowsAWTWGLGraphicsConfigurationFactory.java:182) at com.jogamp.nativewindow.GraphicsConfigurationFactory.chooseGraphicsConfiguration(GraphicsConfigurationFactory.java:424) at com.jogamp.opengl.awt.GLCanvas.chooseGraphicsConfiguration(GLCanvas.java:1512) at com.jogamp.opengl.awt.GLCanvas.addNotify(GLCanvas.java:607) at java.desktop/java.awt.Container.addNotify(Container.java:2804) at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4839) at java.desktop/java.awt.Container.addNotify(Container.java:2804) at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4839) at java.desktop/java.awt.Container.addNotify(Container.java:2804) at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4839) at java.desktop/javax.swing.JRootPane.addNotify(JRootPane.java:729) at java.desktop/java.awt.Container.addNotify(Container.java:2804) at java.desktop/java.awt.Window.addNotify(Window.java:791) at java.desktop/java.awt.Frame.addNotify(Frame.java:495) at java.desktop/java.awt.Window.pack(Window.java:826) at net.sf.openrocket.gui.figure3d.photo.PhotoFrame$4.<init>(PhotoFrame.java:122) at net.sf.openrocket.gui.figure3d.photo.PhotoFrame.<init>(PhotoFrame.java:118) at net.sf.openrocket.gui.figure3d.photo.PhotoFrame.<init>(PhotoFrame.java:71) at net.sf.openrocket.gui.main.BasicFrame$19.actionPerformed(BasicFrame.java:692) at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972) at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313) at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374) at com.github.weisj.darklaf.ui.menu.DarkMenuItemUIBase.doClick(DarkMenuItemUIBase.java:174) at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1072) at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626) at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389) at java.desktop/java.awt.Component.processEvent(Component.java:6391) at java.desktop/java.awt.Container.processEvent(Container.java:2266) at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001) at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324) at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833) at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948) at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575) at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516) at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310) at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780) at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833) at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773) at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722) at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716) at java.base/java.security.AccessController.doPrivileged(AccessController.java:399) at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97) at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746) at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744) at java.base/java.security.AccessController.doPrivileged(AccessController.java:399) at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743) at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
> 
> ---------- Thread information ----------
> Thread[AWT-EventQueue-0,6,main]
> 
> ---------- System information ----------
> OpenRocket version: 23.09.beta.01
> OpenRocket source: default
> OpenRocket location: \\Mac\Home\Desktop\Sibo\Projects\OpenRocket\Software\openrocket\swing\build\jar\OpenRocket.jar
> User-defined thrust curves location: C:\Users\SiboVanGool\AppData\Roaming\OpenRocket\ThrustCurves
> LAF: com.github.weisj.darklaf.DarkLaf
> JOGL version: 2.5.0
> Current default locale: en
> System properties:
> apple.laf.useScreenMenuBar=true
> file.encoding=Cp1252
> file.separator=\
> java.class.path=\\Mac\Home\Desktop\Sibo\Projects\OpenRocket\Software\openrocket\swing\build\jar\OpenRocket.jar
> java.class.version=61.0
> java.home=C:\Program Files\Java\jdk-17.0.2
> java.io.tmpdir=C:\Users\SIBOVA~1\AppData\Local\Temp\
> java.library.path=C:\Program Files\Java\jdk-17.0.2\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files\Parallels\Parallels Tools\Applications;C:\TwinCAT\Common64;C:\TwinCAT\Common32;C:\Program Files\Java\jdk-17.0.2\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Git\cmd;C:\Program Files\apache-ant-1.10.12\bin;C:\Ruby31-x64\bin;C:\Users\SiboVanGool\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Java\jdk-17.0.2\bin;C:\Users\SiboVanGool\.dotnet\tools;C:\Program Files\OpenSSL-Win64\bin;;.
> java.runtime.name=Java(TM) SE Runtime Environment
> java.runtime.version=17.0.2+8-LTS-86
> java.specification.name=Java Platform API Specification
> java.specification.vendor=Oracle Corporation
> java.specification.version=17
> java.util.Arrays.useLegacyMergeSort=true
> java.vendor=Oracle Corporation
> java.vendor.url=https://java.oracle.com/
> java.vendor.url.bug=https://bugreport.java.com/bugreport/
> java.version=17.0.2
> java.version.date=2022-01-18
> java.vm.compressedOopsMode=32-bit
> java.vm.info=mixed mode, sharing
> java.vm.name=Java HotSpot(TM) 64-Bit Server VM
> java.vm.specification.name=Java Virtual Machine Specification
> java.vm.specification.vendor=Oracle Corporation
> java.vm.specification.version=17
> java.vm.vendor=Oracle Corporation
> java.vm.version=17.0.2+8-LTS-86
> jdk.debug=release
> jnlp.jogamp.tmp.cache.root=jln11221975726411143493
> line.separator=\u000d\u000a
> native.encoding=Cp1252
> os.arch=amd64
> os.name=Windows 11
> os.version=10.0
> path.separator=;
> sun.arch.data.model=64
> sun.awt.enableExtraMouseButtons=true
> sun.awt.exception.handler=net.sf.openrocket.gui.main.SwingExceptionHandler$AwtHandler
> sun.boot.library.path=C:\Program Files\Java\jdk-17.0.2\bin
> sun.cpu.endian=little
> sun.cpu.isalist=amd64
> sun.io.unicode.encoding=UnicodeLittle
> sun.java.command=\\Mac\Home\Desktop\Sibo\Projects\OpenRocket\Software\openrocket\swing\build\jar\OpenRocket.jar
> sun.java.launcher=SUN_STANDARD
> sun.jnu.encoding=Cp1252
> sun.management.compiler=HotSpot 64-Bit Tiered Compilers
> sun.os.patch.level=
> sun.stderr.encoding=cp437
> sun.stdout.encoding=cp437
> swing.aatext=true
> user.country=US
> user.dir=C:\Users\SiboVanGool
> user.home=C:\Users\SiboVanGool
> user.language=en
> user.name=SiboVanGool
> user.script=
> user.timezone=Europe/Budapest
> user.variant=

### To Reproduce

Just open PhotoStudio

### OpenRocket version

unstable

### What platform are you running on?

Windows

### Additional context

NOTE: this issue only arises when disabling off-screen rendering in the preferences, I have no issue when it's enabled.

**Comment by SiboVG** [comment]
Fixed by #2350.
