### ISSUE TITLE
[Bug] Test failure: info.openrocket.core.simulation.FlightEventsTest testMultiStage

### ISSUE THREAD

**Issue by Laura7089** [openrocket/openrocket#2601]
### Describe the bug

The test in the title fails:

```
...
info.openrocket.core.simulation.FlightEventsTest

  Test testMultiStage() FAILED

  org.opentest4j.AssertionFailedError: Branch 1 FlightEvent 6 type [FlightEvent.Flig
htEvent.Type.GROUND_HIT] has wrong time  ==> expected: <17.78> but was: <17.72582641
9786436>
      at app/org.junit.jupiter.api@5.10.2/org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
      at app/org.junit.jupiter.api@5.10.2/org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
      at app/org.junit.jupiter.api@5.10.2/org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
      at app/org.junit.jupiter.api@5.10.2/org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:86)
      at app/org.junit.jupiter.api@5.10.2/org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1024)
      at app/info.openrocket.core@23.09.SNAPSHOT/info.openrocket.core.simulation.FlightEventsTest.checkEvents(FlightEventsTest.java:194)
      at app/info.openrocket.core@23.09.SNAPSHOT/info.openrocket.core.simulation.FlightEventsTest.testMultiStage(FlightEventsTest.java:153)
      at java.base@17.0.13/java.lang.reflect.Method.invoke(Method.java:569)
      at java.base@17.0.13/java.util.ArrayList.forEach(ArrayList.java:1511)
      at java.base@17.0.13/java.util.ArrayList.forEach(ArrayList.java:1511)

  Test testSingleStage() PASSED
...
```

### To Reproduce

1. Run unit tests.

### OpenRocket version

commit e84145ef9

### What platform are you running on?

Linux

**Comment by JoePfeiffer** [comment]
The time accuracy required to pass that test is probably a little tight.  Typically if you run the test again it'll pass.
