### ISSUE TITLE
Java Error: Illegal Access on start

### ISSUE THREAD

**Issue by everton3x** [openrocket/openrocket#380]
---------- Bug report ----------

Please include a description about what actions you were performing when the exception occurred:
JRE 9.0.1 build 9.0.1+11 amd64

Windows 10 64 bits

(Do not modify anything below this line.)
---------- Exception stack trace ----------
java.lang.RuntimeException: Error starting OpenRocket
	at net.sf.openrocket.startup.jij.JarInJarStarter.runMain(JarInJarStarter.java:40)
	at net.sf.openrocket.startup.OpenRocket.main(OpenRocket.java:32)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.sf.openrocket.startup.jij.JarInJarStarter.runMain(JarInJarStarter.java:38)
	... 1 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source)
	at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source)
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(Unknown Source)
	at net.sf.openrocket.startup.SwingStartup.main(SwingStartup.java:76)
	... 6 more
Caused by: com.google.inject.internal.util.$ComputationException: com.google.inject.internal.util.$ComputationException: java.lang.NoClassDefFoundError: javax/script/ScriptEngineFactory
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553)
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419)
	at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
	at com.google.inject.internal.FailableCache.get(FailableCache.java:50)
	at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:49)
	at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:125)
	at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:521)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:847)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:772)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:256)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:205)
	at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:853)
	at com.google.inject.internal.FactoryProxy.notify(FactoryProxy.java:46)
	at com.google.inject.internal.ProcessedBindingData.runCreationListeners(ProcessedBindingData.java:50)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:133)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.Guice.createInjector(Guice.java:95)
	at com.google.inject.Guice.createInjector(Guice.java:72)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at net.sf.openrocket.startup.SwingStartup.runInEDT(SwingStartup.java:143)
	at net.sf.openrocket.startup.SwingStartup.access$000(SwingStartup.java:43)
	at net.sf.openrocket.startup.SwingStartup$1.run(SwingStartup.java:79)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$500(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: com.google.inject.internal.util.$ComputationException: java.lang.NoClassDefFoundError: javax/script/ScriptEngineFactory
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553)
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419)
	at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
	at com.google.inject.internal.FailableCache.get(FailableCache.java:50)
	at com.google.inject.internal.MembersInjectorStore.get(MembersInjectorStore.java:65)
	at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:73)
	at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:28)
	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:36)
	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:32)
	at com.google.inject.internal.FailableCache$1.apply(FailableCache.java:39)
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549)
	... 35 more
Caused by: java.lang.NoClassDefFoundError: javax/script/ScriptEngineFactory
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.base/java.lang.Class.getDeclaredMethods(Unknown Source)
	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:662)
	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:356)
	at com.google.inject.internal.ConstructorBindingImpl.getInternalDependencies(ConstructorBindingImpl.java:151)
	at com.google.inject.internal.InjectorImpl.getInternalDependencies(InjectorImpl.java:585)
	at com.google.inject.internal.InjectorImpl.cleanup(InjectorImpl.java:543)
	at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:529)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:847)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:772)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:256)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:205)
	at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:853)
	at com.google.inject.internal.SingleFieldInjector.<init>(SingleFieldInjector.java:41)
	at com.google.inject.internal.MembersInjectorStore.getInjectors(MembersInjectorStore.java:125)
	at com.google.inject.internal.MembersInjectorStore.createWithListeners(MembersInjectorStore.java:95)
	at com.google.inject.internal.MembersInjectorStore.access$000(MembersInjectorStore.java:34)
	at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:42)
	at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:39)
	at com.google.inject.internal.FailableCache$1.apply(FailableCache.java:39)
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549)
	... 45 more
Caused by: java.lang.ClassNotFoundException: javax.script.ScriptEngineFactory
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 67 more

---------- Thread information ----------
Thread[main,5,main]

---------- System information ----------
OpenRocket version: 15.03
OpenRocket source: default
OpenRocket location: C:\Users\Everton\Downloads\OpenRocket-15.03.jar
JOGL version: 2.1.5
Current default locale: pt_BR
System properties:
  awt.toolkit=sun.awt.windows.WToolkit
  file.encoding=Cp1252
  file.encoding.pkg=sun.io
  file.separator=\
  java.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment
  java.awt.printerjob=sun.awt.windows.WPrinterJob
  java.class.path=OpenRocket-15.03.jar
  java.class.version=53.0
  java.home=C:\Program Files\Java\jre-9.0.1
  java.io.tmpdir=C:\Users\Everton\AppData\Local\Temp\
  java.library.path=C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\SQL Anywhere 11\bin64;C:\Program Files\SQL Anywhere 11\bin32;C:\Program Files\SafeNet\Authentication\SAC\x64;C:\Program Files\SafeNet\Authentication\SAC\x32;C:\Program Files\Calibre2\;C:\Program Files\Java\jdk-9.0.1\bin;C:\Program Files\Java\jre-9.0.1\bin;e:\composer;C:\Users\Everton\AppData\Local\Microsoft\WindowsApps;E:\tool\shortcut;C:\Program Files\Microsoft VS Code\bin;E:\php\7.1.10_ts_x64;C:\Users\Everton\AppData\Local\atom\bin;C:\Users\Everton\AppData\Roaming\Composer\vendor\bin;C:\Users\Everton\AppData\Local\GitHubDesktop\bin;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;;.
  java.runtime.name=Java(TM) SE Runtime Environment
  java.runtime.version=9.0.1+11
  java.specification.name=Java Platform API Specification
  java.specification.vendor=Oracle Corporation
  java.specification.version=9
  java.vendor=Oracle Corporation
  java.vendor.url=http://java.oracle.com/
  java.vendor.url.bug=http://bugreport.java.com/bugreport/
  java.version=9.0.1
  java.vm.compressedOopsMode=32-bit
  java.vm.info=mixed mode
  java.vm.name=Java HotSpot(TM) 64-Bit Server VM
  java.vm.specification.name=Java Virtual Machine Specification
  java.vm.specification.vendor=Oracle Corporation
  java.vm.specification.version=9
  java.vm.vendor=Oracle Corporation
  java.vm.version=9.0.1+11
  jdk.debug=release
  line.separator=\u000d\u000a
  os.arch=amd64
  os.name=Windows 10
  os.version=10.0
  path.separator=;
  sun.arch.data.model=64
  sun.awt.enableExtraMouseButtons=true
  sun.awt.exception.handler=net.sf.openrocket.gui.main.SwingExceptionHandler$AwtHandler
  sun.boot.library.path=C:\Program Files\Java\jre-9.0.1\bin
  sun.cpu.endian=little
  sun.cpu.isalist=amd64
  sun.desktop=windows
  sun.io.unicode.encoding=UnicodeLittle
  sun.java.command=OpenRocket-15.03.jar
  sun.java.launcher=SUN_STANDARD
  sun.jnu.encoding=Cp1252
  sun.management.compiler=HotSpot 64-Bit Tiered Compilers
  sun.os.patch.level=
  sun.stderr.encoding=cp850
  sun.stdout.encoding=cp850
  user.country=BR
  user.dir=C:\Users\Everton\Downloads
  user.home=C:\Users\Everton
  user.language=pt
  user.name=Everton
  user.script=
  user.timezone=America/Sao_Paulo
  user.variant=
---------- Error log ----------
   1      0,001 INFO   (SwingStartup.java:61) Starting up OpenRocket version 15.03
   2      0,001 INFO   (SwingStartup.java:64) Checking for graphics head
   3      0,002 INFO   (SwingStartup.java:75) Moving startup to EDT
   4      0,117 INFO   (SwingStartup.java:129) Initializing the splash screen
   5      0,205 INFO   (SwingStartup.java:133) Registering exception handler
   6      0,211 INFO   (SwingStartup.java:139) Loading databases
   7      0,930 ERROR  (SwingExceptionHandler.java:48) Handling uncaught exception on thread=Thread[main,5,main]
   > java.lang.RuntimeException: Error starting OpenRocket
   > 	at net.sf.openrocket.startup.jij.JarInJarStarter.runMain(JarInJarStarter.java:40)
   > 	at net.sf.openrocket.startup.OpenRocket.main(OpenRocket.java:32)
   > Caused by: java.lang.reflect.InvocationTargetException
   > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
   > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
   > 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
   > 	at net.sf.openrocket.startup.jij.JarInJarStarter.runMain(JarInJarStarter.java:38)
   > 	... 1 more
   > Caused by: java.lang.reflect.InvocationTargetException
   > 	at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source)
   > 	at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source)
   > 	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(Unknown Source)
   > 	at net.sf.openrocket.startup.SwingStartup.main(SwingStartup.java:76)
   > 	... 6 more
   > Caused by: com.google.inject.internal.util.$ComputationException: com.google.inject.internal.util.$ComputationException: java.lang.NoClassDefFoundError: javax/script/ScriptEngineFactory
   > 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553)
   > 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419)
   > 	at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
   > 	at com.google.inject.internal.FailableCache.get(FailableCache.java:50)
   > 	at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:49)
   > 	at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:125)
   > 	at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:521)
   > 	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:847)
   > 	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:772)
   > 	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:256)
   > 	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:205)
   > 	at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:853)
   > 	at com.google.inject.internal.FactoryProxy.notify(FactoryProxy.java:46)
   > 	at com.google.inject.internal.ProcessedBindingData.runCreationListeners(ProcessedBindingData.java:50)
   > 	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:133)
   > 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
   > 	at com.google.inject.Guice.createInjector(Guice.java:95)
   > 	at com.google.inject.Guice.createInjector(Guice.java:72)
   > 	at com.google.inject.Guice.createInjector(Guice.java:62)
   > 	at net.sf.openrocket.startup.SwingStartup.runInEDT(SwingStartup.java:143)
   > 	at net.sf.openrocket.startup.SwingStartup.access$000(SwingStartup.java:43)
   > 	at net.sf.openrocket.startup.SwingStartup$1.run(SwingStartup.java:79)
   > 	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
   > 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
   > 	at java.desktop/java.awt.EventQueue.access$500(Unknown Source)
   > 	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
   > 	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
   > 	at java.base/java.security.AccessController.doPrivileged(Native Method)
   > 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
   > 	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
   > 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
   > 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
   > 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
   > 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
   > 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
   > 	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
   > Caused by: com.google.inject.internal.util.$ComputationException: java.lang.NoClassDefFoundError: javax/script/ScriptEngineFactory
   > 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553)
   > 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419)
   > 	at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
   > 	at com.google.inject.internal.FailableCache.get(FailableCache.java:50)
   > 	at com.google.inject.internal.MembersInjectorStore.get(MembersInjectorStore.java:65)
   > 	at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:73)
   > 	at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:28)
   > 	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:36)
   > 	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:32)
   > 	at com.google.inject.internal.FailableCache$1.apply(FailableCache.java:39)
   > 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549)
   > 	... 35 more
   > Caused by: java.lang.NoClassDefFoundError: javax/script/ScriptEngineFactory
   > 	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
   > 	at java.base/java.lang.Class.privateGetDeclaredMethods(Unknown Source)
   > 	at java.base/java.lang.Class.getDeclaredMethods(Unknown Source)
   > 	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:662)
   > 	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:356)
   > 	at com.google.inject.internal.ConstructorBindingImpl.getInternalDependencies(ConstructorBindingImpl.java:151)
   > 	at com.google.inject.internal.InjectorImpl.getInternalDependencies(InjectorImpl.java:585)
   > 	at com.google.inject.internal.InjectorImpl.cleanup(InjectorImpl.java:543)
   > 	at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:529)
   > 	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:847)
   > 	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:772)
   > 	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:256)
   > 	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:205)
   > 	at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:853)
   > 	at com.google.inject.internal.SingleFieldInjector.<init>(SingleFieldInjector.java:41)
   > 	at com.google.inject.internal.MembersInjectorStore.getInjectors(MembersInjectorStore.java:125)
   > 	at com.google.inject.internal.MembersInjectorStore.createWithListeners(MembersInjectorStore.java:95)
   > 	at com.google.inject.internal.MembersInjectorStore.access$000(MembersInjectorStore.java:34)
   > 	at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:42)
   > 	at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:39)
   > 	at com.google.inject.internal.FailableCache$1.apply(FailableCache.java:39)
   > 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549)
   > 	... 45 more
   > Caused by: java.lang.ClassNotFoundException: javax.script.ScriptEngineFactory
   > 	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
   > 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
   > 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
   > 	... 67 more
  53      0,000 STDERR (-) ===== 45 STDERR lines removed =====
  53      0,933 STDERR (SwingExceptionHandler.java:49) 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
  54      0,933 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
  55      0,933 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
  56      0,933 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
  57      0,933 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
  58      0,933 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
  59      0,933 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
  60      0,933 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
  61      0,934 STDERR (SwingExceptionHandler.java:49) Caused by: com.google.inject.internal.util.$ComputationException: java.lang.NoClassDefFoundError: javax/script/ScriptEngineFactory
  62      0,934 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553)
  63      0,934 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419)
  64      0,934 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
  65      0,934 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.FailableCache.get(FailableCache.java:50)
  66      0,934 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.MembersInjectorStore.get(MembersInjectorStore.java:65)
  67      0,934 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:73)
  68      0,934 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:28)
  69      0,934 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:36)
  70      0,934 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:32)
  71      0,934 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.FailableCache$1.apply(FailableCache.java:39)
  72      0,934 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549)
  73      0,934 STDERR (SwingExceptionHandler.java:49) 	... 35 more
  74      0,934 STDERR (SwingExceptionHandler.java:49) Caused by: java.lang.NoClassDefFoundError: javax/script/ScriptEngineFactory
  75      0,934 STDERR (SwingExceptionHandler.java:49) 	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
  76      0,934 STDERR (SwingExceptionHandler.java:49) 	at java.base/java.lang.Class.privateGetDeclaredMethods(Unknown Source)
  77      0,934 STDERR (SwingExceptionHandler.java:49) 	at java.base/java.lang.Class.getDeclaredMethods(Unknown Source)
  78      0,934 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:662)
  79      0,935 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:356)
  80      0,935 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.ConstructorBindingImpl.getInternalDependencies(ConstructorBindingImpl.java:151)
  81      0,935 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.InjectorImpl.getInternalDependencies(InjectorImpl.java:585)
  82      0,935 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.InjectorImpl.cleanup(InjectorImpl.java:543)
  83      0,935 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:529)
  84      0,935 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:847)
  85      0,935 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:772)
  86      0,935 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:256)
  87      0,935 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:205)
  88      0,935 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:853)
  89      0,935 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.SingleFieldInjector.<init>(SingleFieldInjector.java:41)
  90      0,935 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.MembersInjectorStore.getInjectors(MembersInjectorStore.java:125)
  91      0,935 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.MembersInjectorStore.createWithListeners(MembersInjectorStore.java:95)
  92      0,935 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.MembersInjectorStore.access$000(MembersInjectorStore.java:34)
  93      0,935 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:42)
  94      0,935 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:39)
  95      0,935 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.FailableCache$1.apply(FailableCache.java:39)
  96      0,935 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549)
  97      0,935 STDERR (SwingExceptionHandler.java:49) 	... 45 more
  98      0,935 STDERR (SwingExceptionHandler.java:49) Caused by: java.lang.ClassNotFoundException: javax.script.ScriptEngineFactory
  99      0,935 STDERR (SwingExceptionHandler.java:49) 	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
 100      0,935 STDERR (SwingExceptionHandler.java:49) 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
 101      0,936 STDERR (SwingExceptionHandler.java:49) 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
 102      0,936 STDERR (SwingExceptionHandler.java:49) 	... 67 more
 103      0,936 INFO   (SwingExceptionHandler.java:64) Exception handler not on EDT, invoking dialog on EDT
 104      0,937 INFO   (SwingExceptionHandler.java:201) Showing Exception dialog
 105      4,352 USER   (SwingExceptionHandler.java:220) User requested sending bug report
 106      4,357 DEBUG  (JarUtil.java:40) Found jar file using codeSource
---------- End of bug report ----------

**Comment by wcravens** [comment]
Please include a description about what actions you were performing when the exception occurred:

**Comment by everton3x** [comment]
On start splash screen

**Comment by tibbe** [comment]
This could be #346.

**Comment by andreybolonin** [comment]
<img width="744" alt="screen shot 2017-11-30 at 5 40 44 pm" src="https://user-images.githubusercontent.com/2576509/33439301-c81a5c84-d5f5-11e7-887c-c321d0c2f812.png">

**Comment by itshanney** [comment]
This should all be resolved now with latest builds after upgrading to Java 9. For 15.03 release, Java 8 is still required and will not work with Java 9+. Closing for now and please re-open if there's a fresh occurrence.
