### ISSUE TITLE
Flat NoseCone geometries may calculate Negative Volume and Inertia

### ISSUE THREAD

**Issue by teyrana** [openrocket/openrocket#406]
Reported on mailing list:
```
---------- Exception stack trace ----------
java.lang.reflect.InvocationTargetException
	at java.awt.EventQueue.invokeAndWait(Unknown Source)
	at java.awt.EventQueue.invokeAndWait(Unknown Source)
	at javax.swing.SwingUtilities.invokeAndWait(Unknown Source)
	at net.sf.openrocket.startup.SwingStartup.main(SwingStartup.java:76)
Caused by: net.sf.openrocket.util.BugException: BUG:   attempted to initialize an InertiaMatrix with a negative inertia value.
	at net.sf.openrocket.masscalc.RigidBody.<init>(RigidBody.java:24)
	at net.sf.openrocket.masscalc.MassCalculation.calculateAssembly(MassCalculation.java:279)
	at net.sf.openrocket.masscalc.MassCalculation.calculateAssembly(MassCalculation.java:310)
	at net.sf.openrocket.masscalc.MassCalculation.calculateAssembly(MassCalculation.java:310)
	at net.sf.openrocket.masscalc.MassCalculator.calculate(MassCalculator.java:105)
        . . .
```

**Comment by teyrana** [comment]
Closed as resolved.  (FIx merge in MR #407)
