### ISSUE TITLE
Engine reference error while generating DesignReport

### ISSUE THREAD

**Issue by teyrana** [openrocket/openrocket#429]
---------- Bug report ----------
1. Attempting to 'Print/Export to PDF': 
2. specify filename, 
3. components to output
4. click 'save to pdf'
5.  (wait)
6. the following exception is thrown:

```
---------- Exception stack trace ----------
java.lang.IllegalStateException: Attempted to add motor data with an invalid fcid
	at net.sf.openrocket.gui.print.DesignReport.addMotorData(DesignReport.java:332)
	at net.sf.openrocket.gui.print.DesignReport.writeToDocument(DesignReport.java:244)
	at net.sf.openrocket.gui.print.PrintController.print(PrintController.java:74)
	at net.sf.openrocket.gui.dialogs.PrintDialog.generateReport(PrintDialog.java:289)
	at net.sf.openrocket.gui.dialogs.PrintDialog.onSavePDF(PrintDialog.java:356)
	at net.sf.openrocket.gui.dialogs.PrintDialog.access$5(PrintDialog.java:327)
	at net.sf.openrocket.gui.dialogs.PrintDialog$4.actionPerformed(PrintDialog.java:180)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
        ....
```

**Comment by wolsen** [comment]
This was fixed in commit 6dae530a and resolved with issue #531
