### ISSUE TITLE
Crashes on starting

### ISSUE THREAD

**Issue by greenpdx** [openrocket/openrocket#735]
---------- Bug report ----------

Please include a description about what actions you were performing when the exception occurred:

I just run
java -jar OpenRocket-15.03.jar

Include your email address (optional; it helps if we can contact you in case we need additional information):

(Do not modify anything below this line.)
---------- Exception stack trace ----------
java.lang.RuntimeException: Error starting OpenRocket
	at net.sf.openrocket.startup.jij.JarInJarStarter.runMain(JarInJarStarter.java:40)
	at net.sf.openrocket.startup.OpenRocket.main(OpenRocket.java:32)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.sf.openrocket.startup.jij.JarInJarStarter.runMain(JarInJarStarter.java:38)
	... 1 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1367)
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1342)
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
	at net.sf.openrocket.startup.SwingStartup.main(SwingStartup.java:76)
	... 6 more
Caused by: com.google.inject.internal.util.$ComputationException: com.google.inject.internal.util.$ComputationException: java.lang.NoClassDefFoundError: javax/script/ScriptEngineFactory
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553)
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419)
	at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
	at com.google.inject.internal.FailableCache.get(FailableCache.java:50)
	at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:49)
	at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:125)
	at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:521)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:847)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:772)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:256)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:205)
	at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:853)
	at com.google.inject.internal.FactoryProxy.notify(FactoryProxy.java:46)
	at com.google.inject.internal.ProcessedBindingData.runCreationListeners(ProcessedBindingData.java:50)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:133)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.Guice.createInjector(Guice.java:95)
	at com.google.inject.Guice.createInjector(Guice.java:72)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at net.sf.openrocket.startup.SwingStartup.runInEDT(SwingStartup.java:143)
	at net.sf.openrocket.startup.SwingStartup.access$000(SwingStartup.java:43)
	at net.sf.openrocket.startup.SwingStartup$1.run(SwingStartup.java:79)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: com.google.inject.internal.util.$ComputationException: java.lang.NoClassDefFoundError: javax/script/ScriptEngineFactory
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553)
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419)
	at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
	at com.google.inject.internal.FailableCache.get(FailableCache.java:50)
	at com.google.inject.internal.MembersInjectorStore.get(MembersInjectorStore.java:65)
	at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:73)
	at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:28)
	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:36)
	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:32)
	at com.google.inject.internal.FailableCache$1.apply(FailableCache.java:39)
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549)
	... 34 more
Caused by: java.lang.NoClassDefFoundError: javax/script/ScriptEngineFactory
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2309)
	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:662)
	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:356)
	at com.google.inject.internal.ConstructorBindingImpl.getInternalDependencies(ConstructorBindingImpl.java:151)
	at com.google.inject.internal.InjectorImpl.getInternalDependencies(InjectorImpl.java:585)
	at com.google.inject.internal.InjectorImpl.cleanup(InjectorImpl.java:543)
	at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:529)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:847)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:772)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:256)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:205)
	at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:853)
	at com.google.inject.internal.SingleFieldInjector.<init>(SingleFieldInjector.java:41)
	at com.google.inject.internal.MembersInjectorStore.getInjectors(MembersInjectorStore.java:125)
	at com.google.inject.internal.MembersInjectorStore.createWithListeners(MembersInjectorStore.java:95)
	at com.google.inject.internal.MembersInjectorStore.access$000(MembersInjectorStore.java:34)
	at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:42)
	at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:39)
	at com.google.inject.internal.FailableCache$1.apply(FailableCache.java:39)
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549)
	... 44 more
Caused by: java.lang.ClassNotFoundException: javax.script.ScriptEngineFactory
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 66 more

---------- Thread information ----------
Thread[main,5,main]

---------- System information ----------
OpenRocket version: 15.03
OpenRocket source: default
OpenRocket location: /home/savages/Downloads/OpenRocket-15.03.jar
JOGL version: 2.1.5
Current default locale: en_US
System properties:
  awt.toolkit=sun.awt.X11.XToolkit
  file.encoding=UTF-8
  file.separator=/
  java.awt.graphicsenv=sun.awt.X11GraphicsEnvironment
  java.awt.printerjob=sun.print.PSPrinterJob
  java.class.path=OpenRocket-15.03.jar
  java.class.version=55.0
  java.home=/usr/lib/jvm/java-11-openjdk-amd64
  java.io.tmpdir=/tmp
  java.library.path=/usr/java/packages/lib:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
  java.runtime.name=OpenJDK Runtime Environment
  java.runtime.version=11.0.8+10-post-Ubuntu-0ubuntu118.04.1
  java.specification.name=Java Platform API Specification
  java.specification.vendor=Oracle Corporation
  java.specification.version=11
  java.vendor=Ubuntu
  java.vendor.url=https://ubuntu.com/
  java.vendor.url.bug=https://bugs.launchpad.net/ubuntu/+source/openjdk-lts
  java.version=11.0.8
  java.version.date=2020-07-14
  java.vm.compressedOopsMode=Zero based
  java.vm.info=mixed mode, sharing
  java.vm.name=OpenJDK 64-Bit Server VM
  java.vm.specification.name=Java Virtual Machine Specification
  java.vm.specification.vendor=Oracle Corporation
  java.vm.specification.version=11
  java.vm.vendor=Ubuntu
  java.vm.version=11.0.8+10-post-Ubuntu-0ubuntu118.04.1
  jdk.debug=release
  line.separator=\u000a
  os.arch=amd64
  os.name=Linux
  os.version=5.3.0-62-generic
  path.separator=:
  sun.arch.data.model=64
  sun.awt.enableExtraMouseButtons=true
  sun.awt.exception.handler=net.sf.openrocket.gui.main.SwingExceptionHandler$AwtHandler
  sun.boot.library.path=/usr/lib/jvm/java-11-openjdk-amd64/lib
  sun.cpu.endian=little
  sun.cpu.isalist=
  sun.desktop=gnome
  sun.font.fontmanager=sun.awt.X11FontManager
  sun.io.unicode.encoding=UnicodeLittle
  sun.java.command=OpenRocket-15.03.jar --illegal-access=warn
  sun.java.launcher=SUN_STANDARD
  sun.jnu.encoding=UTF-8
  sun.management.compiler=HotSpot 64-Bit Tiered Compilers
  sun.os.patch.level=unknown
  user.country=US
  user.dir=/home/savages/Downloads
  user.home=/home/savages
  user.language=en
  user.name=savages
  user.timezone=America/Los_Angeles
---------- Error log ----------
   1      0.000 INFO   (SwingStartup.java:61) Starting up OpenRocket version 15.03
   2      0.000 INFO   (SwingStartup.java:64) Checking for graphics head
   3      0.002 INFO   (SwingStartup.java:75) Moving startup to EDT
   4      0.703 INFO   (SwingStartup.java:129) Initializing the splash screen
   5      0.806 INFO   (SwingStartup.java:133) Registering exception handler
   6      0.813 INFO   (SwingStartup.java:139) Loading databases
   7      1.314 ERROR  (SwingExceptionHandler.java:48) Handling uncaught exception on thread=Thread[main,5,main]
   > java.lang.RuntimeException: Error starting OpenRocket
   > 	at net.sf.openrocket.startup.jij.JarInJarStarter.runMain(JarInJarStarter.java:40)
   > 	at net.sf.openrocket.startup.OpenRocket.main(OpenRocket.java:32)
   > Caused by: java.lang.reflect.InvocationTargetException
   > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   > 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   > 	at net.sf.openrocket.startup.jij.JarInJarStarter.runMain(JarInJarStarter.java:38)
   > 	... 1 more
   > Caused by: java.lang.reflect.InvocationTargetException
   > 	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1367)
   > 	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1342)
   > 	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
   > 	at net.sf.openrocket.startup.SwingStartup.main(SwingStartup.java:76)
   > 	... 6 more
   > Caused by: com.google.inject.internal.util.$ComputationException: com.google.inject.internal.util.$ComputationException: java.lang.NoClassDefFoundError: javax/script/ScriptEngineFactory
   > 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553)
   > 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419)
   > 	at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
   > 	at com.google.inject.internal.FailableCache.get(FailableCache.java:50)
   > 	at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:49)
   > 	at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:125)
   > 	at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:521)
   > 	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:847)
   > 	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:772)
   > 	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:256)
   > 	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:205)
   > 	at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:853)
   > 	at com.google.inject.internal.FactoryProxy.notify(FactoryProxy.java:46)
   > 	at com.google.inject.internal.ProcessedBindingData.runCreationListeners(ProcessedBindingData.java:50)
   > 	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:133)
   > 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
   > 	at com.google.inject.Guice.createInjector(Guice.java:95)
   > 	at com.google.inject.Guice.createInjector(Guice.java:72)
   > 	at com.google.inject.Guice.createInjector(Guice.java:62)
   > 	at net.sf.openrocket.startup.SwingStartup.runInEDT(SwingStartup.java:143)
   > 	at net.sf.openrocket.startup.SwingStartup.access$000(SwingStartup.java:43)
   > 	at net.sf.openrocket.startup.SwingStartup$1.run(SwingStartup.java:79)
   > 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
   > 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
   > 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
   > 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
   > 	at java.base/java.security.AccessController.doPrivileged(Native Method)
   > 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
   > 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
   > 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
   > 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
   > 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
   > 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
   > 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
   > 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
   > Caused by: com.google.inject.internal.util.$ComputationException: java.lang.NoClassDefFoundError: javax/script/ScriptEngineFactory
   > 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553)
   > 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419)
   > 	at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
   > 	at com.google.inject.internal.FailableCache.get(FailableCache.java:50)
   > 	at com.google.inject.internal.MembersInjectorStore.get(MembersInjectorStore.java:65)
   > 	at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:73)
   > 	at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:28)
   > 	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:36)
   > 	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:32)
   > 	at com.google.inject.internal.FailableCache$1.apply(FailableCache.java:39)
   > 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549)
   > 	... 34 more
   > Caused by: java.lang.NoClassDefFoundError: javax/script/ScriptEngineFactory
   > 	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
   > 	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
   > 	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2309)
   > 	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:662)
   > 	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:356)
   > 	at com.google.inject.internal.ConstructorBindingImpl.getInternalDependencies(ConstructorBindingImpl.java:151)
   > 	at com.google.inject.internal.InjectorImpl.getInternalDependencies(InjectorImpl.java:585)
   > 	at com.google.inject.internal.InjectorImpl.cleanup(InjectorImpl.java:543)
   > 	at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:529)
   > 	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:847)
   > 	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:772)
   > 	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:256)
   > 	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:205)
   > 	at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:853)
   > 	at com.google.inject.internal.SingleFieldInjector.<init>(SingleFieldInjector.java:41)
   > 	at com.google.inject.internal.MembersInjectorStore.getInjectors(MembersInjectorStore.java:125)
   > 	at com.google.inject.internal.MembersInjectorStore.createWithListeners(MembersInjectorStore.java:95)
   > 	at com.google.inject.internal.MembersInjectorStore.access$000(MembersInjectorStore.java:34)
   > 	at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:42)
   > 	at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:39)
   > 	at com.google.inject.internal.FailableCache$1.apply(FailableCache.java:39)
   > 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549)
   > 	... 44 more
   > Caused by: java.lang.ClassNotFoundException: javax.script.ScriptEngineFactory
   > 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
   > 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
   > 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
   > 	... 66 more
  52      0.000 STDERR (-) ===== 44 STDERR lines removed =====
  52      1.318 STDERR (SwingExceptionHandler.java:49) 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
  53      1.318 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
  54      1.318 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
  55      1.318 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
  56      1.318 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
  57      1.318 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
  58      1.318 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
  59      1.319 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
  60      1.319 STDERR (SwingExceptionHandler.java:49) Caused by: com.google.inject.internal.util.$ComputationException: java.lang.NoClassDefFoundError: javax/script/ScriptEngineFactory
  61      1.319 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553)
  62      1.319 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419)
  63      1.319 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
  64      1.319 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.FailableCache.get(FailableCache.java:50)
  65      1.319 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.MembersInjectorStore.get(MembersInjectorStore.java:65)
  66      1.319 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:73)
  67      1.319 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:28)
  68      1.319 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:36)
  69      1.319 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:32)
  70      1.320 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.FailableCache$1.apply(FailableCache.java:39)
  71      1.320 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549)
  72      1.320 STDERR (SwingExceptionHandler.java:49) 	... 34 more
  73      1.320 STDERR (SwingExceptionHandler.java:49) Caused by: java.lang.NoClassDefFoundError: javax/script/ScriptEngineFactory
  74      1.320 STDERR (SwingExceptionHandler.java:49) 	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
  75      1.320 STDERR (SwingExceptionHandler.java:49) 	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
  76      1.320 STDERR (SwingExceptionHandler.java:49) 	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2309)
  77      1.320 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:662)
  78      1.320 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:356)
  79      1.320 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.ConstructorBindingImpl.getInternalDependencies(ConstructorBindingImpl.java:151)
  80      1.320 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.InjectorImpl.getInternalDependencies(InjectorImpl.java:585)
  81      1.320 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.InjectorImpl.cleanup(InjectorImpl.java:543)
  82      1.320 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:529)
  83      1.320 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:847)
  84      1.320 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:772)
  85      1.320 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:256)
  86      1.321 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:205)
  87      1.321 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:853)
  88      1.321 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.SingleFieldInjector.<init>(SingleFieldInjector.java:41)
  89      1.321 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.MembersInjectorStore.getInjectors(MembersInjectorStore.java:125)
  90      1.321 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.MembersInjectorStore.createWithListeners(MembersInjectorStore.java:95)
  91      1.321 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.MembersInjectorStore.access$000(MembersInjectorStore.java:34)
  92      1.321 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:42)
  93      1.321 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:39)
  94      1.321 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.FailableCache$1.apply(FailableCache.java:39)
  95      1.321 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549)
  96      1.321 STDERR (SwingExceptionHandler.java:49) 	... 44 more
  97      1.321 STDERR (SwingExceptionHandler.java:49) Caused by: java.lang.ClassNotFoundException: javax.script.ScriptEngineFactory
  98      1.321 STDERR (SwingExceptionHandler.java:49) 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
  99      1.321 STDERR (SwingExceptionHandler.java:49) 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
 100      1.321 STDERR (SwingExceptionHandler.java:49) 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
 101      1.321 STDERR (SwingExceptionHandler.java:49) 	... 66 more
 102      1.321 INFO   (SwingExceptionHandler.java:64) Exception handler not on EDT, invoking dialog on EDT
 103      1.322 INFO   (SwingExceptionHandler.java:201) Showing Exception dialog
 104      6.533 USER   (SwingExceptionHandler.java:220) User requested sending bug report
 105      6.537 DEBUG  (JarUtil.java:40) Found jar file using codeSource
---------- End of bug report ----------

**Comment by JoePfeiffer** [comment]
OpenRocket 15.03 will not run with versions of Java more recent than Java8 (from the system information in your bug report, you appear to be running java-11-openjdk-amd64).  The current development version, which we're hoping to be able to release soon, will run on more recent versions of Java.

In the mean time, your best bet is to download the Linux appimage at https://github.com/openrocket/openrocket/releases/download/release-15.03/OpenRocket-15.03.AppImage
make it executable, and run that.

**Comment by greenpdx** [comment]
thanks
