### ISSUE TITLE
Upgrading to Java 15 causes unit test failures

### ISSUE THREAD

**Issue by JoePfeiffer** [openrocket/openrocket#826]
Updating to either
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)
or
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.23.0, JRE 15 Linux amd64-64-Bit Compressed References 20201022_81 (JIT enabled, AOT enabled)
under Linux results in the following two unit test failures:

TestScriptingUtil	testGetLanguages	Failure	N/A
junit.framework.AssertionFailedError
at net.sf.openrocket.simulation.extension.impl.TestScriptingUtil.testGetLanguages(TestScriptingUtil.java:41)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

TestScriptingUtil	testGetLanguage	Failure	expected:<JavaScript> but was:<null>
junit.framework.AssertionFailedError: expected:<JavaScript> but was:<null>
at net.sf.openrocket.simulation.extension.impl.TestScriptingUtil.testGetLanguage(TestScriptingUtil.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

I'm not getting the unit test failures with Java 14.

**Comment by hcraigmiller** [comment]
Where we will now be looking at JAVA 17 LTS compatibility, I recommend closing this issue.

**Comment by JoePfeiffer** [comment]
Unless the problem still exists under 17, of course. Needs to be checked.

**Comment by SiboVG** [comment]
This issue still exists under Java 17
